import { useState } from 'react'
import type { FaultType, InjectionSpec, State, Variable } from './types'

const variables: Variable[] = ['temperature_c', 'pressure_hpa', 'humidity_pct']
const faults: FaultType[] = ['spike', 'freeze', 'drift', 'bias', 'noise', 'missing']
const names: Record<Variable, string> = { temperature_c: 'Temperature', pressure_hpa: 'Pressure', humidity_pct: 'Humidity' }
const units: Record<Variable, string> = { temperature_c: '°C', pressure_hpa: 'hPa', humidity_pct: '%' }
const title = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase())
const time = (value: string | null) => value ? new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC' }) + ' UTC' : 'N/A'
const reading = (value: number | null, unit: string) => value == null ? 'N/A' : `${value.toFixed(1)} ${unit}`

export default function SimulationLab({ state, command, mutate }: { state: State; command: (cmd: string, extras?: object) => void; mutate: (path: string, init: RequestInit) => Promise<State> }) {
  const defaultRow = (): InjectionSpec => ({ station_id: state.stations[0]?.station_id ?? 'CHD-01', variable: 'temperature_c', fault_type: 'spike', magnitude: 9, duration_samples: 1 })
  const [drafts, setDrafts] = useState<InjectionSpec[]>([defaultRow()])
  const [duration, setDuration] = useState(12)
  const [faultError, setFaultError] = useState('')
  const update = (index: number, patch: Partial<InjectionSpec>) => setDrafts(rows => rows.map((row, i) => i === index ? { ...row, ...patch } : row))
  const liveStatus = state.source_status.find(s => s.source_mode === 'live')
  const liveReadings = state.recent_observations.filter(o => o.source_mode === 'live' && o.sequence === state.sequence)
  const inject = async () => {
    try {
      await mutate(`/runs/${state.run_id}/injections/batch`, { method: 'POST', body: JSON.stringify({ injections: drafts }) })
      setFaultError('')
      setDrafts([defaultRow()])
    } catch (error) { setFaultError(String(error)) }
  }
  return <>
    <div className="page-head"><div><p className="eyebrow">CONTROLLED DEMONSTRATION</p><h1>Simulation Lab</h1><p>Changes to copied observations pass through the backend Trust Engine.</p></div><span className="timestamp">Frame {state.sequence} · {time(state.source_timestamp)}</span></div>
    <section className="panel"><div className="panel-head"><h3>Source and replay</h3><span>{title(state.status)}</span></div>
      <div className="control-grid"><div><span className="control-label">Source</span><div className="segments">{(['replay', 'live'] as const).map(mode => <button key={mode} className={state.source_mode === mode ? 'active' : ''} aria-pressed={state.source_mode === mode} onClick={() => command('set_source', { source_mode: mode })}>{mode === 'replay' ? 'Prepared replay' : 'Genuine live'}</button>)}</div></div><div><span className="control-label">Replay speed</span><div className="segments">{([1, 10, 60] as const).map(speed => <button key={speed} className={state.speed === speed ? 'active' : ''} aria-pressed={state.speed === speed} onClick={() => command('set_speed', { speed })}>{speed}×</button>)}</div></div><div className="button-row"><button className="primary" onClick={() => command(state.status === 'running' ? 'pause' : 'play')}>{state.status === 'running' ? 'Pause' : 'Play / Resume'}</button><button onClick={() => command('step')}>Next frame</button><button onClick={() => { if (window.confirm('Reset this run and clear incidents and injections?')) command('reset') }}>Reset</button></div></div>
      <p className="muted">{state.source_mode === 'replay' ? 'Every speed processes every source frame. Reset returns to the prepared baseline paused.' : 'Live values are Open-Meteo gridded current weather. Next frame fetches or checks the provider; a test copy may reuse the same genuine provider timestamp.'}</p>
      {state.source_mode === 'live' && <p className={liveStatus?.status === 'available' ? 'info' : 'warning'}>{liveStatus?.source_name ?? 'Open-Meteo'}: {title(liveStatus?.status ?? 'unavailable')} · provider {time(liveStatus?.source_timestamp ?? null)} · fetched {time(liveStatus?.fetched_at ?? null)}. {liveStatus?.detail}</p>}
    </section>
    <section className="panel"><div className="panel-head"><h3>Fault batch</h3><span>{drafts.length}/8 pending · same next-frame boundary</span></div>
      <div className="draft-list">{drafts.map((draft, index) => <div className="fault-draft" key={index}>
        <div className="fault-title"><strong>Fault {index + 1}</strong><button className="link" disabled={drafts.length === 1} onClick={() => setDrafts(rows => rows.filter((_, i) => i !== index))}>Remove</button></div>
        <div className="fault-fields"><div><span className="control-label">Location</span><div className="segments station-choices">{state.stations.map(station => <button key={station.station_id} className={draft.station_id === station.station_id ? 'active' : ''} aria-pressed={draft.station_id === station.station_id} onClick={() => update(index, { station_id: station.station_id })}>{station.name}</button>)}</div></div>
          <div><span className="control-label">Variable</span><div className="segments">{variables.map(variable => <button key={variable} className={draft.variable === variable ? 'active' : ''} aria-pressed={draft.variable === variable} onClick={() => update(index, { variable })}>{names[variable]}</button>)}</div></div></div>
        <span className="control-label">Fault type</span><div className="fault-choices">{faults.map(fault => <button key={fault} className={draft.fault_type === fault ? 'active' : ''} aria-pressed={draft.fault_type === fault} onClick={() => update(index, { fault_type: fault, magnitude: fault === 'freeze' || fault === 'missing' ? 0 : draft.magnitude || 9 })}>{title(fault)}</button>)}</div>
        <div className="fault-numbers"><label>Magnitude {draft.fault_type === 'drift' ? `(total ${units[draft.variable]})` : units[draft.variable]}<input type="number" min="-50" max="50" step="0.5" value={draft.magnitude} disabled={draft.fault_type === 'freeze' || draft.fault_type === 'missing'} onChange={e => update(index, { magnitude: Number(e.target.value) })} /></label><label>Duration in source samples<input type="number" min="1" max="24" value={draft.duration_samples} onChange={e => update(index, { duration_samples: Number(e.target.value) })} /></label></div>
      </div>)}</div><div className="button-row"><button disabled={drafts.length >= 8} onClick={() => setDrafts(rows => [...rows, defaultRow()])}>Add Fault</button><button className="primary" onClick={() => void inject().catch(() => {})}>Inject All</button></div>
      {faultError && <p className="warning" role="alert">{faultError}</p>}
      <p className="muted">A scheduled fault waits for the next processed frame. Live faults transform a preserved test copy only; provider values stay unchanged.</p>
    </section>
    {state.source_mode === 'live' && <section className="panel"><div className="panel-head"><h3>RAW LIVE observations and test copies</h3><span>{time(state.source_timestamp)}</span></div>{liveReadings.length ? <div className="table-wrap"><table><thead><tr><th>Location / variable</th><th>RAW LIVE</th><th>TEST COPY</th><th>Assessment</th></tr></thead><tbody>{liveReadings.map(o => { const assessment = state.latest_assessments.find(a => a.sample_id === o.sample_id); return <tr key={o.sample_id}><td>{state.stations.find(s => s.station_id === o.station_id)?.name ?? o.station_id}<small>{names[o.variable]}</small></td><td>{reading(o.raw_value, o.unit)}</td><td>{o.is_test_overlay ? reading(o.value, o.unit) : '—'}</td><td>{assessment?.trust_score == null ? `N/A · ${title(assessment?.assessment_status ?? 'unavailable')}` : `Trust ${assessment.trust_score}/100 · ${title(assessment.decision)}`}</td></tr> })}</tbody></table></div> : <p className="empty">{liveStatus?.status === 'unavailable' ? 'Provider unavailable. No live values or test copy can be shown.' : 'Waiting for genuine current weather observations.'}</p>}</section>}
    <div className="two-col"><section className="panel"><div className="panel-head"><h3>Fault progression</h3><span>{state.active_injections.filter(i => i.status === 'scheduled' || i.status === 'active').length} pending or active</span></div>{state.active_injections.length ? state.active_injections.slice(-12).reverse().map(injection => <div className="priority-row" key={injection.injection_id}><span><strong>{state.stations.find(s => s.station_id === injection.station_id)?.name ?? injection.station_id} · {names[injection.variable]} · {title(injection.fault_type)}</strong><small>{title(injection.status)} · {injection.remaining_samples} samples remaining · starts frame {injection.start_sequence}{injection.status === 'scheduled' && state.status !== 'running' ? ' · waiting for next frame' : ''}</small></span>{(injection.status === 'scheduled' || injection.status === 'active') && <button onClick={() => void mutate(`/runs/${state.run_id}/injections/${injection.injection_id}`, { method: 'DELETE' }).catch(() => {})}>Cancel</button>}</div>) : <p className="empty">No faults scheduled in this run.</p>}</section>
      <section className="panel"><div className="panel-head"><h3>Regional weather change</h3><span>Replay only</span></div><p>Coherent temperature, pressure and humidity movement across all {state.stations.length} locations. Independent faults can run during the event.</p><div className="button-row"><label>Duration in samples<input type="number" min="4" max="48" value={duration} onChange={e => setDuration(Number(e.target.value))} /></label><button className="primary" disabled={state.source_mode !== 'replay'} title={state.source_mode !== 'replay' ? 'Switch to replay for regional weather' : ''} onClick={() => void mutate(`/runs/${state.run_id}/regional-events`, { method: 'POST', body: JSON.stringify({ duration_samples: duration }) }).catch(() => {})}>Start Regional Weather Change</button></div>{state.regional_event && state.sequence < state.regional_event.end_sequence && <p className="info">Frames {state.regional_event.start_sequence}–{state.regional_event.end_sequence - 1} · {state.sequence < state.regional_event.start_sequence ? 'Scheduled' : 'Active'}</p>}</section></div>
  </>
}
