export type Variable = 'temperature_c' | 'pressure_hpa' | 'humidity_pct'
export type FaultType = 'spike' | 'freeze' | 'drift' | 'bias' | 'noise' | 'missing'
export interface Station { station_id: string; name: string; pole_id: string; maintenance_email?: string | null; latitude: number; longitude: number; criticality: number; status: 'genuine' | 'review' | 'fault' | 'unknown' }
export interface Observation { sample_id: string; run_id: string; generation: number; sequence: number; station_id: string; timestamp: string; variable: Variable; value: number | null; unit: string; source_mode: 'replay' | 'live'; source_name: string; source_timestamp: string; received_at: string; is_test_overlay: boolean; raw_value: number | null }
export interface Evidence { kind: string; label: string; detail: string; support: number; available: boolean }
export interface Assessment { sample_id: string; station_id: string; variable: Variable; timestamp: string; assessment_status: string; trust_score: number | null; trust_band: string | null; decision: 'likely_fault' | 'needs_review' | 'likely_genuine'; confidence: number; severity: string; fault_type: string; expected_value: number | null; peer_value: number | null; observed_value: number | null; explanation: string; resolution: string; evidence: Evidence[] }
export interface SensorHealth { station_id: string; variable: Variable; health_score: number | null; health_status: string; maintenance_priority: number; recommendation: string; updated_at: string; trend: number[] }
export interface InjectionSpec { station_id: string; variable: Variable; fault_type: FaultType; magnitude: number; duration_samples: number }
export interface Injection extends InjectionSpec { injection_id: string; start_sequence: number; end_sequence: number; status: string; remaining_samples: number }
export interface Incident { incident_id: string; station_id: string; variable: Variable; opened_at: string; last_seen_at: string; status: string; fault_type: string; severity: string; confidence: number; duration_samples: number; maintenance_priority: number; health_score: number | null; recommendation: string; task_status: string; assignee_id: string | null }
export interface User { id: string; username: string; display_name: string; role: 'authority' | 'employee'; active: number }
export interface Task { incident_id: string; assignee_id: string | null; status: string; station_id: string; station_name: string; pole_id: string; variable: Variable; fault_type: string; severity: string; opened_at: string; updated_at: string; trust_score: number | null; confidence: number; assessment_status: string; expected_value: number | null; explanation: string; resolution: string }
export interface AuthorityNotification { id: string; incident_id: string; station_id: string; actor_user_id: string; event_type: string; title: string; body: string; created_at: string; read_at: string | null }
export interface OperatorAction { action_id: string; incident_id: string; action: string; timestamp: string }
export interface SourceStatus { source_mode: 'replay' | 'live'; source_name: string; provenance_type: string; status: 'available' | 'unavailable'; source_timestamp: string | null; fetched_at: string | null; detail: string; variables: Variable[] }
export interface State { contract_version: string; run_id: string; generation: number; state_version: number; status: string; speed: number; source_mode: 'replay' | 'live'; sequence: number; source_timestamp: string | null; stations: Station[]; recent_observations: Observation[]; latest_assessments: Assessment[]; recent_assessments: Assessment[]; sensor_health: SensorHealth[]; active_incidents: Incident[]; maintenance_items: Incident[]; active_injections: Injection[]; regional_event: { name: string; start_sequence: number; end_sequence: number; duration_samples: number } | null; source_status: SourceStatus[]; operator_actions: OperatorAction[] }
